[package]
name = "tari_comms_dht"
version = "0.0.5"
authors = ["The Tari Development Community"]
description = "Tari comms DHT module"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tari_comms = { version = "^0.0", path = "../"}
tari_crypto = { version = "^0.0", path = "../../infrastructure/crypto"}
tari_utilities = { version = "^0.0", path = "../../infrastructure/tari_util"}
tari_comms_middleware = { version = "^0.0", path = "../middleware"}

futures= {version= "0.3.0-alpha.18", package="futures-preview"}
rand = "0.5.5"
serde = "1.0.90"
serde_derive = "1.0.90"
tokio = "0.2.0-alpha.4"
tower= "0.3.0-alpha.1a"
tracing = "0.1.9"
serde_repr = "0.1.5"
digest = "0.8.1"
