[package]
name = "tari_mmr"
authors = ["The Tari Development Community"]
description = "A Merkle Mountain Range implementation"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.10.1"
edition = "2018"

[features]
default = ["native_bitmap"]
native_bitmap = ["croaring"]
benches = ["criterion"]

[dependencies]
tari_utilities = "^0.3"

criterion = { version="0.2", optional = true }
croaring =  { version = "=0.4.5", optional = true }
digest = "0.9.0"
log = "0.4"
serde = { version = "1.0.97", features = ["derive"] }
thiserror = "1.0.26"

[dev-dependencies]
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", branch = "main" }
tari_infra_derive= { path = "../../infrastructure/derive" }

bincode = "1.1"
blake2 = "0.9.0"
rand="0.8.0"
serde_json = "1.0"

[lib]
# Disable libtest from intercepting Criterion bench arguments
bench = false

[[bench]]
name = "bench"
harness = false
