[workspace]

members = [
    "base_layer/core",
    "base_layer/keymanager",
    "base_layer/mmr",
    "base_layer/mining",
    "base_layer/p2p",
    "base_layer/service_framework",
    "base_layer/wallet",
    "comms",
    "digital_assets_layer/core",
    "infrastructure/broadcast_channel",
    "infrastructure/crypto",
    "infrastructure/pubsub",
    "infrastructure/storage",
    "infrastructure/test_utils",
    "applications/grpc_wallet",
    "applications/console_text_messenger",
    "ffi"
]
