[package]
name = "tari_mining_node"
authors = ["The Tari Development Community"]
description = "The tari mining node implementation"
repository = "https://github.com/tari-project/tari"
license = "BSD-3-Clause"
version = "0.10.1"
edition = "2018"

[dependencies]
tari_app_grpc = {  path = "../tari_app_grpc" }
tari_app_utilities = { path = "../tari_app_utilities"}
tari_common = {  path = "../../common" }
tari_core = { path = "../../base_layer/core",  default-features = false }

bufstream = "0.1"
chrono = "0.4"
crossbeam = "0.8"
futures = "0.3"
hex = "0.4.2"
jsonrpc = "0.11.0"
log = { version = "0.4", features = ["std"] }
native-tls = "0.2"
num_cpus = "1.13"
prost-types = "0.8"
rand = "0.8"
reqwest = { version = "0.11", features = [ "json"] }
serde = { version = "1.0", default_features = false, features = ["derive"] }
serde_json = "1.0.57"
sha3 = "0.9"
thiserror = "1.0"
time = "0.1"
tokio = { version = "1.11", default_features = false, features = ["rt-multi-thread"] }
tonic = { version = "0.5.2", features = ["transport"] }

[dev-dependencies]
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", branch = "main" }

prost-types = "0.8"
chrono = "0.4"
