[package]
name = "tari_shutdown"
description = "A convenient shutdown signal"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures =  { version = "=0.3.0-alpha.19", package = "futures-preview"}

[dev-dependencies]
tokio = "0.2.0-alpha.6"
