[package]
name = "tari_common_types"
authors = ["The Tari Development Community"]
description = "Tari cryptocurrency common types"
license = "BSD-3-Clause"
version = "0.10.1"
edition = "2018"

[dependencies]
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", branch = "main" }

digest = "0.9.0"
futures = { version = "^0.3.1", features = ["async-await"] }
lazy_static = "1.4.0"
rand = "0.8"
serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "1.11", features = ["time", "sync"] }
