########################################################################################################################
#                                                                                                                      #
#                                          TestNet Miner Configuration Options                                         #
#                                                                                                                      #
########################################################################################################################


wallet_address = "http://[::1]:50051"
base_node_address = "http://[::1]:50052"
