[package]
name = "wallet_ffi"
version = "0.0.5"
edition = "2018"

[dependencies]
tari_comms = { path = "../../comms", version = "^0.0"}
tari_comms_dht = { path = "../../comms/dht", version = "^0.0"}
tari_crypto = { path = "../../infrastructure/crypto", version = "^0.0" }
tari_p2p = {path = "../p2p", version = "^0.0"}
tari_utilities = { path = "../../infrastructure/tari_util", version = "^0.0"}
tari_wallet = { path = "../wallet", version = "^0.0", features = ["test_harness", "c_integration"]}

futures =  { version = "^0.3.1", features =["compat", "std"]}
tokio = "0.2.10"
libc = "0.2.65"
rand = "0.7.2"
chrono = { version = "0.4.6", features = ["serde"]}
tari_broadcast_channel = { version="^0.0",  path = "../../infrastructure/broadcast_channel" }
derive-error = "0.0.4"
log = "0.4.6"

[lib]
crate-type = ["staticlib","cdylib"]

[dev-dependencies]
tempdir = "0.3.7"
lazy_static = "1.3.0"

[dependencies.tari_core]
path = "../../base_layer/core"
version = "^0.0"
default-features = false
features = ["transactions"]