[package]
name = "tari_wallet"
version = "0.0.2"
edition = "2018"

[dependencies]
tari_core = { path = "../core", version="^0.0"}
tari_crypto = { path = "../../infrastructure/crypto", version = "^0.0" }
tari_utilities = { path = "../../infrastructure/tari_util", version = "^0.0"}
tari_comms = { path = "../../comms", version = "^0.0"}
tari_p2p = {path = "../p2p", version = "^0.0"}
chrono = { version = "0.4.6", features = ["serde"]}
derive-error = "0.0.4"
digest = "0.8.0"
serde = {version = "1.0.89", features = ["derive"] }

[dev-dependencies]
rand = "0.5"


