[package]
name = "tari_service_framework"
version = "0.0.5"
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.28"
tower-service = "0.2.0"
derive-error = "0.0.4"

[dev-dependencies]
tokio-mock-task = "0.1.1"
tower-util = "0.1.0"
tokio = "0.1.22"
