[package]
name = "tari_common"
authors = ["The Tari Development Community"]
description = "Utilities and features for the Tari domain layer, shared across both Base and Digital Asset layers."
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"


[dependencies]
clap = "2.33.0"
config = { version = "0.9.3" }
dirs = "2.0"
get_if_addrs = "0.5.3"
log = "0.4.8"
log4rs = "0.8.3"
multiaddr={package="parity-multiaddr", version = "0.7.2"}

[dev-dependencies]
tempdir = "0.3.7"
