on:
  push:
    branches:
      - development

name: Version

jobs:
  bump:
    name: patch crate versions
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: |
          echo "this is a lot faster than building from source 🤷"
          curl -o /tmp/cws -L https://github.com/delta1/cargo-workspaces/releases/download/v0.2.23-build/cargo-workspaces-x86_64-linux-gnu
          chmod +x /tmp/cws
      - name: git config
        run: |
          git config --global user.name "Tari Deploy"
          git config --global user.email "bug_reports@tari.com"
      - name: crates list
        run: |
          pwd
          /tmp/cws workspaces list
      - name: bump patch version
        run: |
          /tmp/cws workspaces version patch \
          --no-git-tag \
          --no-global-tag \
          --force "*" \
          -y \
          -m "ci: bump crate versions to %v" \
          --allow-branch development
