on:
  push:
    branches:
      - development
      - workspace-versioning

name: Version

jobs:
  bump:
    name: patch crate versions
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.TARI_DEPLOY_SECRET_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
      - name: temp
        run: |
          git config --list
      - name: install
        run: |
          echo "this is a lot faster than building from source 🤷"
          curl -o /tmp/cws -L https://github.com/delta1/cargo-workspaces/releases/download/v0.2.24/cargo-workspaces-v0.2.24-x86_64-linux-gnu
          chmod +x /tmp/cws
      - name: git config
        run: |
          git config --global user.name "tari-deploy"
          git config --global user.email "bug_reports@tari.com"
      - name: crates list
        run: |
          pwd
          /tmp/cws workspaces list
      - name: bump patch version
        run: |
          /tmp/cws workspaces version patch \
          --no-git-tag \
          --sign-commit \
          --no-global-tag \
          --force "*" \
          -y \
          -m "ci: bump crate versions to %v" \
          --allow-branch workspace-versioning
