[package]
name = "tari_stratum_ffi"
authors = ["The Tari Development Community"]
description = "Tari cryptocurrency miningcore C FFI bindings"
license = "BSD-3-Clause"
version = "0.10.1"
edition = "2018"

[dependencies]
tari_comms = { path = "../../comms" }
tari_crypto = { git = "https://github.com/tari-project/tari-crypto.git", branch = "main" }
tari_common = {  path = "../../common" }
tari_app_grpc = { path = "../../applications/tari_app_grpc" }
tari_core = { path = "../../base_layer/core", default-features = false, features = ["transactions"] }
tari_utilities = "^0.3"

hex = "0.4.2"
libc = "0.2.65"
serde = { version="1.0.106", features = ["derive"] }
serde_json = "1.0.57"
thiserror = "1.0.26"

[lib]
crate-type = ["staticlib","cdylib"]
